# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_lmutils_wrappers", use_symbols = TRUE, package_name = "lmutils")

#' @docType package
#' @usage NULL
#' @useDynLib lmutils, .registration = TRUE
NULL

#' Convert files from one format to another.
#' `from` and `to` must be character vectors of the same length.
#' @export
convert_files <- function(from, to, item_type) .Call(wrap__convert_files, from, to, item_type)

#' Calculate R^2 and adjusted R^2 for a block and outcomes.
#' `data` is a character vector of file names, a list of matrices, or a single matrix.
#' `outcomes` is a file name or a matrix.
#' Returns a data frame with columns `r2`, `adj_r2`, `data`, and `outcome`.
#' @export
calculate_r2 <- function(data, outcomes) .Call(wrap__calculate_r2, data, outcomes)

#' Calculate R^2 and adjusted R^2 for ranges of a data matrix and outcomes.
#' `data` is a string file name or a matrix.
#' `outcomes` is a string file name or a matrix.
#' `ranges` is a matrix with 2 columns, the start and end columns to use (inclusive).
#' Returns a data frame with columns `r2`, `adj_r2`, and `outcome` corresponding to each range.
#' @export
calculate_r2_ranges <- function(data, outcomes, ranges) .Call(wrap__calculate_r2_ranges, data, outcomes, ranges)

#' Combine matrices into a single matrix.
#' `data` is a character vector of file names or a list of matrices.
#' `out` is a file name to write the combined matrix to.
#' If `out` is `NULL`, the combined matrix is returned otherwise `NULL`.
#' @export
combine_matrices <- function(data, out) .Call(wrap__combine_matrices, data, out)

#' Remove rows from a matrix.
#' `data` is a character vector of file names, a list of matrices, or a single matrix.
#' `rows` is a vector of row indices to remove (1-based).
#' `out` is a file name to write the matrix with the rows removed to.
#' If `out` is `NULL`, the matrix with the rows removed is returned otherwise `NULL`.
#' @export
remove_rows <- function(data, rows, out) .Call(wrap__remove_rows, data, rows, out)

#' Save a matrix to a file.
#' `mat` must be a double matrix.
#' `out` is the name of the file to save to.
#' @export
save_matrix <- function(mat, out) .Call(wrap__save_matrix, mat, out)

#' Convert a data frame to a file.
#' `df` must be a numeric data frame, numeric matrix, or a string RData file name.
#' `out` is the name of the file to save to.
#' If `out` is `NULL`, the matrix is returned otherwise `NULL`.
#' @export
to_matrix <- function(df, out) .Call(wrap__to_matrix, df, out)

#' Computes the cross product of the matrix. Equivalent to `t(data) %*% data`.
#' `data` must be a string file name or a matrix.
#' `out` is the name of the file to save to.
#' If `out` is `NULL`, the cross product is returned otherwise `NULL`.
#' @export
crossprod <- function(data, out) .Call(wrap__crossprod, data, out)

#' Set the log level.
#' `level` is the log level.
#' @export
set_log_level <- function(level) invisible(.Call(wrap__set_log_level, level))

#' Set the number of blocks to process at once.
#' `blocks_per_chunk` is the number of blocks to process at once.
#' @export
set_blocks_at_once <- function(blocks_per_chunk) invisible(.Call(wrap__set_blocks_at_once, blocks_per_chunk))

#' Set the number of threads.
#' `num_threads` is the number of threads.
#' @export
set_num_threads <- function(num_threads) invisible(.Call(wrap__set_num_threads, num_threads))


# nolint end
