name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v1

      - name: Create archive
        run: |
          repo_name=$(basename $(pwd))
          tar -czvf "${repo_name}.tar.gz" .

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF_NAME}" "${repo_name}.tar.gz" --repo "${{ github.repository }}" --clobber
