name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-archive:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create archive
        run: |
          repo_name=$(basename $(pwd))
          git archive --format=tar.gz --prefix="${repo_name}/" -o "${repo_name}.tar.gz" HEAD

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_name=$(basename $(pwd))
          gh release upload "${GITHUB_REF_NAME}" "${repo_name}.tar.gz" --repo "${{ github.repository }}" --clobber
